upgrade deps
Losant/cosa pull request #70
Opened 2023-04-20 20:39 UTC by eeerin

SP-10382

2023-04-20 20:40 UTC, spacetc62 requested changes
```
lib/model.js
11:  pathEq, complement, pick, omit, has, isEmpty, isPlainObject
21:const isNotVirtual = complement(pathEq([ 'type' ], 'virtual'));
```

2023-04-20 20:41 UTC, spacetc62 commented on package.json
>      "mongodb": "~4.14.0",
can bump to [4.16.0](https://www.npmjs.com/package/mongodb/v/4.16.0)

2023-04-21 07:18 UTC, ankit-gautam23 approved these changes
LGTM

2023-04-26 14:05 UTC, spacetc62 approved these changes

2023-04-26 14:05 UTC, merged